import React from 'react'

const s = {
  bar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    padding: '0.85rem 1.25rem',
    background: 'var(--bg-surface)',
    borderTop: '1px solid var(--border)',
    display: 'flex',
    gap: 10,
    maxWidth: 480,
    margin: '0 auto',
    backdropFilter: 'blur(12px)',
  },
  btnSecondary: {
    flex: 1,
    padding: '10px 12px',
    borderRadius: 'var(--radius-sm)',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border-hover)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-main)',
    transition: 'background 0.12s',
  },
  btnPrimary: {
    flex: 2,
    padding: '10px 12px',
    borderRadius: 'var(--radius-sm)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    border: '1px solid var(--accent)44',
    background: 'var(--accent)',
    color: '#0d0f14',
    fontFamily: 'var(--font-main)',
    transition: 'opacity 0.12s',
  },
}

export default function BottomBar({ items, onNewSession }) {
  async function exportPDF() {
    if (items.length === 0) { alert('Add some items first!'); return }
    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ unit: 'mm', format: 'a5' })
      const today = new Date().toLocaleDateString('en-PK', {
        day: 'numeric', month: 'long', year: 'numeric'
      })
      const total = items.reduce((s, i) => s + i.subtotal, 0)

      // Header
      doc.setFillColor(13, 15, 20)
      doc.rect(0, 0, 148, 30, 'F')
      doc.setTextColor(201, 169, 110)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(16)
      doc.text('TROLLEY TRACKER', 14, 14)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(138, 143, 158)
      doc.text(`Shopping Session  ·  ${today}`, 14, 22)

      // Table header
      doc.setTextColor(80, 80, 80)
      doc.setFontSize(8.5)
      doc.setFont('helvetica', 'bold')
      let y = 38
      doc.text('#', 14, y)
      doc.text('Product', 22, y)
      doc.text('Qty', 95, y)
      doc.text('Unit Price', 108, y)
      doc.text('Subtotal', 128, y)

      doc.setDrawColor(220, 220, 220)
      doc.line(14, y + 3, 140, y + 3)
      y += 10

      // Items
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      items.forEach((item, i) => {
        if (y > 175) { doc.addPage(); y = 20 }
        doc.setTextColor(30, 30, 30)
        const shortName = item.name.length > 42 ? item.name.slice(0, 40) + '…' : item.name
        doc.text(`${i + 1}`, 14, y)
        doc.text(shortName, 22, y)
        doc.text(`${item.qty}`, 95, y)
        doc.text(`Rs.${item.price.toFixed(2)}`, 108, y)
        doc.text(`Rs.${item.subtotal.toFixed(2)}`, 128, y)
        y += 8
        if (i % 2 === 0) {
          doc.setFillColor(248, 248, 248)
          doc.rect(13, y - 9, 128, 8, 'F')
          doc.setTextColor(30, 30, 30)
          doc.text(`${i + 1}`, 14, y - 1)
          doc.text(shortName, 22, y - 1)
          doc.text(`${item.qty}`, 95, y - 1)
          doc.text(`Rs.${item.price.toFixed(2)}`, 108, y - 1)
          doc.text(`Rs.${item.subtotal.toFixed(2)}`, 128, y - 1)
          y -= 0
        }
      })

      // Total
      doc.setDrawColor(201, 169, 110)
      doc.setLineWidth(0.5)
      doc.line(14, y + 2, 140, y + 2)
      y += 10
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(11)
      doc.setTextColor(13, 15, 20)
      doc.text('TOTAL', 14, y)
      doc.setTextColor(140, 100, 40)
      doc.text(`Rs. ${total.toFixed(2)}`, 105, y)

      y += 8
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(160, 160, 160)
      doc.text(`${items.length} item${items.length !== 1 ? 's' : ''}  ·  generated by Trolley Tracker`, 14, y)

      doc.save(`trolley-${Date.now()}.pdf`)
    } catch (e) {
      alert('PDF export failed. Please try again.')
      console.error(e)
    }
  }

  function handleNewSession() {
    if (items.length > 0 && !confirm('Start a new session? This will clear all current items.')) return
    onNewSession()
  }

  return (
    <div style={s.bar}>
      <button style={s.btnSecondary} onClick={handleNewSession}>
        ↺ new session
      </button>
      <button style={s.btnPrimary} onClick={exportPDF}>
        ↓ save as PDF
      </button>
    </div>
  )
}
